### ISSUE TITLE
try to run from source

### ISSUE THREAD

**Issue by Aboghazala** [nngogol/PySimpleGUIDesigner#2]
hello,
i tried to run from source i have got this error

```python
$ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from .boilerplate_psg import boilerplate_
ModuleNotFoundError: No module named '__main__.boilerplate_psg'; '__main__' is not a package
```

**Comment by Aboghazala** [comment]
Also i installed the version from pip

```python
pip install PySimpleGUIDesigner
```

it runs ok but doesn't have the options you shows in your youtube video

![image](https://user-images.githubusercontent.com/37757246/60760785-a5ff5700-a03b-11e9-8bcb-94e553d5ffa8.png)

**Comment by nngogol** [comment]
`i tried to run from source i have got this error`
I fixed today. Read readme.md for new examples :)

----


`doesn't have the options you shows in your youtube video`
That's because video is pretty old, **but** it doesn't mean, that it's useless - it means, that GUI for pysimpleguiDesigner has changed. It was written in Qt, but I rewrote it in PySimpleGUI, so in the video you see Qt GUI.

**Comment by nngogol** [comment]
Fixed. Try to download the source code **or** try  running from `pip`
Update with:
```bash
pip install  PySimpleGUIDesigner --no-cache
```
Run:
```bash
PySimpleGUIDesigner
```
